version: '3.9'

services:
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: {}

secrets:
  npmrc:
    file: ./.npmrc_ci
